### ISSUE TITLE
region2/mu-comparison warn when combined symbol length is too great for basename()

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilReports#93]
A simple check on max symbol length should be used to trigger a suggestion on shorter symbol names. Currently, very long symbol names will cause `basename()` to throw an error and stop the report.

A toggle in `config.R` for disabling QC output would be useful for those cases where long symbol names are required.

**Comment by brownag** [comment]
This has been resolved with a warning that will inform the user of the options to customize the default output file names in config.R, reverting to "safe" names in the meantime. Another case of this is when there are many symbols, rather than symbols with long names. This issue will be closed by #107.
